name = "rent"
main = "src/index.js"
compatibility_date = "2026-09-01"

[assets]
directory = "./public"
binding = "ASSETS"

[[kv_namespaces]]
binding = "HOUSE_RENT_KV"
id = "0275b02b5c8047e48c6871b0243bcff1"